apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: {{cookiecutter.component_id | jsonify}}
  description: {{cookiecutter.description | jsonify}}
  annotations: 
    github.com/project-slug: {{cookiecutter.destination.owner + "/" + cookiecutter.destination.repo}}
    sentry.io/project-slug: {{cookiecutter.component_id | jsonify}}
    
spec:
  type: website
  lifecycle: experimental
  owner: {{cookiecutter.owner | jsonify}}
