apiVersion: backstage.io/v1beta2
kind: Template
metadata:
  name: vite
  title: Vite
  description: scaffold 
spec:
  owner: backstage/techdocs-core
  type: website

  parameters:
    - title: Fill in some steps
      required:
        - name
        - owner
      properties:
        name:
          title: Name
          type: string
          description: Unique name of the component
          ui:autofocus: true
          ui:options:
            rows: 5
        description:
          title: Description
          type: string
          description: Help others understand what this website is for.
        owner:
          title: Owner
          type: string
          description: Owner of the component
          ui:field: OwnerPicker
          ui:options:
            allowedKinds: 
              - Group
    - title: Choose a location
      required:
        - repoUrl
      properties:
        repoUrl:
          title: Repository Location
          type: string
          ui:field: RepoUrlPicker
          ui:options:
            allowedHosts:
              - github.com

  steps:
    - id: fetch-base
      name: Fetch Base
      action: fetch:cookiecutter
      input:
        url: "https://github.com/kfsoftware/kfs-vite-template"
        values:
          name: '{{parameters.name}}'
          component_id: '{{parameters.name}}'
          description: '{{parameters.description}}'
          owner: '{{parameters.owner}}'

    - id: publish
      name: Publish
      action: publish:github
      input:
        allowedHosts: ['github.com']
        description: 'This is {{ parameters.name }}'
        repoUrl: '{{ parameters.repoUrl }}'

    - id: vercel
      name: Link project in Vercel
      action: vercel:link
      input:
        projectName: '{{ parameters.name }}'
        outputRepo: 'dist'
        githubRepo: '{{ parameters.repoUrl }}'

    - id: register
      name: Register
      action: catalog:register
      input:
        repoContentsUrl: '{{ steps.publish.output.repoContentsUrl }}'
        catalogInfoPath: '/catalog-info.yaml'


  output:
    links: 
      - url: '{{steps.publish.output.remoteUrl}}'
        text: 'Go to PR'
