apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: {{cookiecutter.component_id | jsonify}}
  description: {{cookiecutter.description | jsonify}}
  annotations: {}
    
spec:
  type: website
  lifecycle: experimental
  owner: {{cookiecutter.owner | jsonify}}
